#+TITLE: 形意-劈拳
#+DATE: <2017-12-10>
#+TAGS: 形意,劈拳,劈,肺
#+LAYOUT: post
#+CATEGORIES: live

* 劈拳
** 古谱
*** 形意拳谱
劈拳性属金，是阴阳连环成一气之起落也，气之一静，故形象太极。

气之一动而生物，其名为横，横属土，土生万物，故内包四拳，其五行循环之理。

土生金，故先练劈拳，上下运用，有劈物之意，其形像斧，故名劈拳。

所诸身内则为肺，劲顺则气合，劲拗则肺气乖。

夫人以气为主，气合则体壮，气乖则体弱，故学者不可大意也。

上步初势曰：两手紧握，同变阴拳，左拳落出，肘顺胸前，高不过肩，力垂左肩，右手靠脐，肘至肋边，眼平舌卷，气降丹田。

*** 劈拳讲义
劈拳性属金，是阴阳连环一气之起落也。

气之一静，故形象太极；气之一动而生物，其名为横。

横属土，土生万物，故内包四拳。

按其五行循环之理，土生金，故先练劈拳，上下运用，有劈物之意，其形似斧，故名劈拳，所诸身内则为肺，劲顺则肺气和，劲谬则肺气乖。

夫人以气为主，气和则体壮，气乖则体弱，故学者不可大意也。

上步初势曰：两手紧握，同变阴拳，左拳落出，肘顺胸前，高不过肩，力垂左肩；右手靠脐，肘至肋边，眼平舌卷，气降丹田。

换步歌：左足既开，右足大进，手足齐落，推挽两迅，左足斜跟，右足仍顺，指开心齐，后手肋近，手足与鼻，列成直阵。

转身歌：起势钻，落势翻，行如槐虫，起如挑担，若遇人多，三摇两旋，正是转身之谓也。

<!--more-->

*** 歌诀
劈拳之形似斧，性属金，崩拳之形似箭，性属木。

双榻双钻气相连，起吸落呼莫等闲。易骨易筋加洗髓，脚踩手劈一气传。

*** 打法
拳打三节不见形，如见形影不为能。

能在一思进，莫在一思存。能在一气先，莫在一气后。

肘打去意占胸膛，起手好似虎扑羊；头打落意随足走，起而未起占中央；脚踏中门抢地位，就是神仙也难防。

肩打一阴反一阳，两手只在洞中藏；左右全凭盖他意，束展二字一命亡。


** 练法
顶、扣、圆、毒、抱、垂、曲、挺。

三顶：头上顶，有冲天之雄，手外顶，有推山之功，舌上顶，有吼狮吞象容。

三扣：肩扣，则气力到肘，膝胯扣则全身气凑，手足指掌扣，则周身力厚。

三圆：脊背圆，其力摧身，前胸圆，则两肘力全，虎口圆，则勇猛外宣。

三毒：心毒如怒狸攫鼠，眼毒知观兔之饥鹰，手毒如扑羊之饿虎。

三抱：(另一说为三敏即心敏、眼敏、手敏是也。)丹田抱气，气不外散，胆量抱身，临事不怯，两肘抱肋，出入不乱。

三垂：气垂则气降丹田，肩垂则肩能摧肘，肘垂则肘能摧手。

三曲：两肱宜曲，曲则力富，两股宜曲，曲则力凑，手腕宜曲，曲则力厚。

三挺：颈挺则精气实顶，腰挺则力达四肢，膝挺则有弹力。

*** 拳法
起钻落翻，要点：虎口成员，力达指尖，钻为辅，劈为主；

切记：拳要劈，而非推，手掌摊开，意到力到。
*** 身法
身体下坐，拧腰送胯，身起拳落。

*** 发力
力量传递：腰为主宰，心到意到气到力到，力量传递沿着督脉一条线，拧腰，坐胯，一伸一缩之间,力量瞬间而至，劲整。

力源在丹田，腰胯（中节），上下两个力，下传于足，上达于指（梢节）。

力量往下，继而向上反弹一个力，或者说力从脚起，至尾椎，经督脉，到达指尖。

要点：要想力整，如何？力不可中断，怎样才能保证不中断呢，就一个字“松”，当然也不可完全松下来，该送的松，凡是适度为要，力量传递过程中，一旦僵硬，则力被阻。
*** 呼吸
初学者应以一呼一动为主，钻吸劈呼。呼吸自然，不可憋气。


** 打法
"束展二字一命亡", 关键在于舒展二字，一收一缩之间，伴随身体整体的移动，产生瞬间爆炸力，身体像一个炮弹似的，一下出去，缩成一团，瞬间炸开，力可想而知。

钻而近身，“劈”，近身发力.


** 医理
劈拳属金，练肺，归肺。

《灵枢·经脉》：

  “肺手太阴之脉，起于中焦，下络大肠，还循胃口，上膈属肺，从肺系横出腋下，下循臑内，行少阴、心主之前，下肘中，循臂内上骨下廉，入寸口，上鱼，循鱼际，出大指之端：其支者，从腕后，直出次指内廉，出其端。”

*** 歌诀
手太阴肺十一穴，中府云门天府诀，侠白尺泽孔最存，列缺经渠太渊涉，鱼际少商如韭叶，左右二十二孔穴。流注线：此一经起于中府，终于少商。

督脉行脉之中行,二十八穴始长强.腰俞阳关入命门,悬枢脊中中枢长.筋缩至阳归灵台,神道身柱陶道开.大椎哑门连风府,脑户强间后顶排.百会前顶通囟会,上星神庭素髎对.水沟兑端在唇上,龈交上齿缝之内.

*** 行功
肺与大肠想表里，主司呼吸，故气力合，声应拳而出.
